version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.18

    steps:
      - checkout

      - run:
          name: Run tests
          command: go test ./...

      - run:
          name: Run linter
          command: go vet ./...

workflows:
  version: 2
  build:
    jobs:
      - build
