version: 2.1

jobs:
  build:
    docker:
      - image: google/dart:2.9.1

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: dart pub get

      - run:
          name: Run tests and analyze
          command: dart test && dart analyze

workflows:
  version: 2
  build:
    jobs:
      - build
